### ISSUE TITLE
Pluralization doesn't work

### ISSUE THREAD

**Issue by adhatama** [qor/i18n#16]
I have a simple pluralization like this:

```
lang/en-US.yml

en-US:
  demo:
    plural: '{{p "Count" (one "{{.Count}} item") (other "{{.Count}} items")}}'
```

```
main.go

I18n := i18n.New(
    yaml.New("lang"),
)
val := I18n.T(
    "en-US",
    "demo.plural",
    map[string]int{"Count": 1},
)
fmt.Println(val)
```

The printed value of `val` is `1 items` where it should be `1 item`
Did I miss something?
